trigger: none

pr: none

schedules:
- cron: "0 11 * * *"
  displayName: Mon through Sun at 3:00 AM (UTC-8:00)
  branches:
    include:
    - master
  always: true

jobs:
- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: build-job.yml
    buildConfig: checked
    platforms:
    - Linux_arm
    - Linux_arm64
    - Linux_x64
    # TODO: re-enable Windows_NT_arm when https://github.com/dotnet/corefx/issues/38863 is resolved
    - Windows_NT_x64
    - Windows_NT_x86
    - Windows_NT_arm64

- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: test-job.yml
    buildConfig: checked
    platforms:
    - Linux_arm
    - Linux_arm64
    - Linux_x64
    # TODO: re-enable Windows_NT_arm when https://github.com/dotnet/corefx/issues/38863 is resolved
    - Windows_NT_x64
    - Windows_NT_x86
    - Windows_NT_arm64
    helixQueueGroup: corefx
    jobParameters:
      testGroup: outerloop
      corefxTests: true
      displayNameArgs: CoreFX
