trigger: none

pr: none

jobs:
- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: build-job.yml
    buildConfig: checked
    platforms:
    - Linux_arm
    - Linux_arm64
    - Linux_x64
    - Windows_NT_x64
    - Windows_NT_x86
    - Windows_NT_arm64

- template: /eng/platform-matrix.yml
  parameters:
    jobTemplate: test-job.yml
    buildConfig: checked
    platforms:
    - Linux_arm
    - Linux_arm64
    - Linux_x64
    - Windows_NT_x64
    - Windows_NT_x86
    - Windows_NT_arm64
    helixQueueGroup: ci
    jobParameters:
      testGroup: outerloop
      readyToRun: true
      displayNameArgs: R2R
